### ISSUE TITLE
Neoid not working with latest Neography (1.0.10)

### ISSUE THREAD

**Issue by pboling** [maxdemarzi/neography#97]
**Update: See [this issue in the neoid repo](https://github.com/elado/neoid/issues/23)**

```
2013-06-17T20:12:56.646445+00:00 app[web.2]: /app/vendor/bundle/ruby/1.9.1/gems/neography-1.0.10/lib/neography/connection.rb:58:in `post_chunked': undefined method `>' for nil:NilClass (NoMethodError)
2013-06-17T20:12:56.646445+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neography-1.0.10/lib/neography/rest/batch.rb:35:in `batch'
2013-06-17T20:12:56.646445+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neography-1.0.10/lib/neography/rest/batch.rb:14:in `execute'
2013-06-17T20:12:56.646445+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neography-1.0.10/lib/neography/rest.rb:357:in `batch'
2013-06-17T20:12:56.646445+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid/batch.rb:89:in `block in flush_batch'
2013-06-17T20:12:56.646445+00:00 app[web.2]:    from /app/vendor/ruby-1.9.3/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
2013-06-17T20:12:56.646445+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid/batch.rb:88:in `flush_batch'
2013-06-17T20:12:56.646445+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid/batch.rb:76:in `run'
2013-06-17T20:12:56.646445+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid.rb:69:in `batch'
2013-06-17T20:12:56.646445+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid.rb:218:in `initialize_subrefs'
2013-06-17T20:12:56.646638+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid.rb:59:in `initialize_server'
2013-06-17T20:12:56.646638+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid.rb:54:in `initialize_all'
2013-06-17T20:12:56.646638+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid/railtie.rb:7:in `block (2 levels) in <class:Railtie>'
```

Is this a bug in neoid?
